# Oefeningen

### 13.2.1

In [1]:
import math

In [2]:
print(math.pi, math.sqrt(64))

3.141592653589793 8.0

In [5]:
def partial_volume(radius):
    """
    Calculates partial volume given a radius.
    :param radius:      float or int
    :return:            partial volume (float)
    """
    return (2/3)*(math.pi*(radius**3))

a = (4.6+1.2)/2.09
b = 3*(4**(7/12))
pv = partial_volume(6)
c = 5*((4+2)/(9*math.sqrt(7)))

print(f'Answers: \n{a}\n{b}\n{pv}\n{c}')

Answers:
2.7751196172248807
6.734772289856238
452.38934211693015
1.259881576697424

### 13.2.2

In [9]:
## A
print("I woke up at eight 'o clock this morning") # fixed by using double quotation marks to wrap the string

## B
name = "John"
age = 42
print('my name is ' + name + ' and my age is ' + str(age)) # Can't concatenate int to str; fixed by making age a string

I woke up at eight 'o clock this morning
my name is John and my age is 42

In [11]:
## C
def circle_area(diameter):
    return math.pi * ((0.5 * diameter) **2 )

print(circle_area(4))

12.566370614359172

In [12]:
## D
# Skipped for now. You know your way around operator precedence.

### 13.2.3

In [15]:
## A
x = 1
y = x + 2
assert y == 3

In [16]:
## C
x = 2
y = 4
z = x**y + 4
assert z == 20

In [18]:
## D
x = 3
y = 5
z = (x + y) / (y - x)
assert z == 4

### 13.2.4

In [22]:
## A
x = 4
y = 5
z = 'hallo'

print(f'A: {x*z}')
print(f'B: {y*str(y)}')
print(f"C: {y}'{x*(str(y)+str(x))}'")

A: hallohallohallohallo
B: 55555
C: 5'54545454'

### 13.2.5

In [23]:
total = 1
fraction = 1
i = 1
for n in range(2, 6):
    i += n
    total += i
    fraction /= i
    print(f'i is now {i}; the cumulative sum is {total} and the cumulative "fraction" is {fraction}')

i is now 3; the cumulative sum is 4 and the cumulative "fraction" is 0.3333333333333333
i is now 6; the cumulative sum is 10 and the cumulative "fraction" is 0.05555555555555555
i is now 10; the cumulative sum is 20 and the cumulative "fraction" is 0.005555555555555555
i is now 15; the cumulative sum is 35 and the cumulative "fraction" is 0.00037037037037037035

### 13.2.6

In [26]:
meters = 234
yards = 0     # 0.9144 m
feet = 0      # 0.3048 m
inches = 0    # 0.54  cm

## My code
yards = meters // 0.9144
remainder = meters % 0.9144

feet = remainder // 0.3048
remainder %= 0.3048

inches = remainder % 0.54

print(f'{meters} metric meters is equivalent to {yards} yards, {feet} feet and {inches} inches')

234 metric meters is equivalent to 255.0 yards, 2.0 feet and 0.21840000000000237 inches

### 13.2.7
Located in `traingle_surface.py`.

### 13.3: Data Types

In [33]:
sentence_lowercase = "the quick brown fox jumps over the lazy dog"
sentence_new = sentence_lowercase.title().replace(' ', '')

print(sentence_capitalize)

TheQuickBrownFoxJumpsOverTheLazyDog

### Practicing with Pandas

In [35]:
import pandas as pd
import numpy as np

In [51]:
df = pd.read_csv('data/train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,493,0,1,"Molson, Mr. Harry Markland",male,55.0,0,0,113787,30.5000,C30,S
1,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
2,388,1,2,"Buss, Miss. Kate",female,36.0,0,0,27849,13.0000,NaN,S
3,192,0,2,"Carbines, Mr. William",male,19.0,0,0,28424,13.0000,NaN,S
4,687,0,3,"Panula, Mr. Jaako Arnold",male,14.0,4,1,3101295,39.6875,NaN,S

In [45]:
df_grouped_by_sex = df.groupby('Sex') # now a groupby object -> can't just print anymore.
df_grouped_by_sex.size()

Sex
female    256
male      456
dtype: int64

In [46]:
df_grouped_by_sex.get_group('female')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
2,388,1,2,"Buss, Miss. Kate",female,36.0,0,0,27849,13.0000,NaN,S
5,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
8,168,0,3,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45.0,1,4,347088,27.9000,NaN,S
10,541,1,1,"Crosby, Miss. Harriet R",female,36.0,0,2,WE/P 5735,71.0000,B22,S
...,...,...,...,...,...,...,...,...,...,...,...,...
701,384,1,1,"Holverson, Mrs. Alexander Oskar (Mary Aline To...",female,35.0,1,0,113789,52.0000,NaN,S
702,313,0,2,"Lahtinen, Mrs. William (Anna Sylfven)",female,26.0,1,1,250651,26.0000,NaN,S
703,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.0,0,2,315153,22.0250,NaN,S
706,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
707,859,1,3,"Baclini, Mrs. Solomon (Latifa Qurban)",female,24.0,0,3,2666,19.2583,NaN,C

In [47]:
## maximum age per group
df_grouped_by_sex.Age.max()

Sex
female    63.0
male      80.0
Name: Age, dtype: float64

In [48]:
## Get more information with the aggregate method
df_grouped_by_sex.Age.agg(['min','max','count','median','mean'],
                          )

         min   max  count  median       mean
Sex
female  0.75  63.0    211    27.0  28.062796
male    0.42  80.0    355    28.0  30.804000

In [49]:
## Adding your own functions
def categorize(x):
    m = x.mean()
    return True if m > 29 else False

df_grouped_by_sex.Age.agg(['max', 'min', categorize])

         max   min  categorize
Sex
female  63.0  0.75       False
male    80.0  0.42        True