# Notebook - Dag 2
> Conda install en PiP install kunnen door elkaar worden gebruikt, mits je alles binnen eenzelfde environment houdt.
> Voor het generaten van een requirements file: `pip freeze > requirements.txt` (Linux)

### Reading and Writing Files

Openen van bestanden met python `open` --> let dat je een bestand altijd moet closen met `close()`, en dat maar 1 process tegelijk naar een bestand kan writen. Beter om deze constructie niet te doen. Gebruik in plaats daarvan een handler.

In [5]:
# with open("C:/Users/jflan/PycharmProjects/ITANN_Data_Science/requirements.txt", mode='r', encoding='utf-8') as file_handler:
#     # data = file_handler.read()   # This is 'Slurping' - don't read whole files in one go!
#     for line in file_handler:
#         print(line.strip())        # .strip removes newline characters (\n, \cr)

### List Comprehension

In [7]:
A = [x**2 for x in range(1,10)]
print(A)

B = []
for x in range(1,10):
    B.append(x**2)

print(B)

[1, 4, 9, 16, 25, 36, 49, 64, 81]
[1, 4, 9, 16, 25, 36, 49, 64, 81]

Voor kleine lists is de tweede methode hierboven sneller; er zit wat overhead in het maken van een comprehension.
Maar voor langere lijsten, of met duurdere operations, is list comprehension sneller, ookal is de tweede ook leesbaarder.

In [9]:
data = ['Hi!', 42, 120, 6, True]
[x**2 if type(x) == 'int' else x*2 for x in data]

['Hi!Hi!', 84, 240, 12, 2]

### Dictionary Comprehension

In [10]:
{x:chr(x) for x in range(0,10)}

{0: '\x00',
 1: '\x01',
 2: '\x02',
 3: '\x03',
 4: '\x04',
 5: '\x05',
 6: '\x06',
 7: '\x07',
 8: '\x08',
 9: '\t'}

### Try and Except
Errors opvangen zodat je code met voorspelbare errors kan omgaan.

In [13]:
L = [1, 2, 3, 4, 5]
try:
    print(L[5])  # Will raise an error, since index 5 is out of bounds for a list of len 5
except:
    print('Nuuuuu! An error!') # Catches ALL errors - not just the Index Out of Bounds!


## Nicer:

try:
    print(L[5])
except IndexError:
    lastval = L[-1]
    print(f"That index is out of bounds, but here is the closest preceding value: {lastval}")
except TypeError:
    print("Encountered a TypeError.")

Nuuuuu! An error!
That index is out of bounds, but here is the closest preceding value: 5

### Regular Expressions
regex101.com
Handige website om regular expressions uit te testen.

In [15]:
import re # Regular Expressions library
mystring = "ACTGCATACGCAGTCAAGCGTACGAT"

pattern = "[0-9]{4}[a-z]{2}" # [ ] : class. { } : quantifier

# Quantifier
## { min, max }
## ? : zero or one
## + : 1 or more
## * : 0 or more

# Classes
## [a-z] [A-Z] [a-zA-Z]
## [0-9] : number between 0 and 9
## [abc] : either a, b, or c

# Anchors (outside parentheses)
## $ : end
## ^ : start

In [22]:
text = "The following telephone the"

pattern = "[Tt]"

re.findall(pattern, text)

['T', 't', 't']

### Object-Oriented Programming

In [50]:
## Classes - what does x have, what can x do?

class Student:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.name_upper()

    def name_upper(self):                  # A method is a function defined within a class, which can be applied to instances
        self.allcaps = self.name.upper()
        return self.allcaps                # of that class. So we can call studentinstance.allcaps

    def __str__(self):
        return f'Instance of Student class\nAttributes: {self.__dict__}'

Jorick = Student('Jorick', 25)
print(Jorick.name, Jorick.age)

## Note that each class inherits the template of an Object class; hence a bunch of dunder methods are already built in.

## You can add things to a class at any time; but adding it to an instance won't add it to other instances.

Marloes = Student('Jorick', 25)

Jorick.cijfers = [8, 7.5, 9.5, 8.5, 10,0]


print(Jorick.cijfers)

try:
    print(Marloes.cijfers)
except AttributeError:
    print("Instance of Student Object 'Marloes' has no attribute 'cijfers'.")

print(f'Trying out our method: {Jorick.allcaps}')

Jorick 25
[8, 7.5, 9.5, 8.5, 10, 0]
Instance of Student Object 'Marloes' has no attribute 'cijfers'.
Trying out our method: JORICK

In [53]:
## Getting nice output out of classes
print(f'{Jorick}')

Instance of Student class
Attributes: {'name': 'Jorick', 'age': 25, 'allcaps': 'JORICK', 'cijfers': [8, 7.5, 9.5, 8.5, 10, 0]}

### Pandas and NumPy
- Turning data into information: "Munging"
- Turning information into knowledge: "Analysis"

- Tidy data: ground level; in a form amenable to data science
- FAIR data: at a high level' in form and storage allowing it to carry on beyond its initial scope, project and group

- R programming language set standard for Tidy Data; book _R for Data Science_ is useful to read even for Python developers.
- Three rules: every variable has a column, every observation has a row, every value in its own cell.

- Codebooks: describes the data; its columns, column descriptions, data types, etcetera - everything someone else needs to understand this dataset and take it up for their own use.

### Fair data:
also known as data stewardship. Meets principles of Findability, accessibility, interoperability, and reusability. Answers the question: _What to do with data once you've tidied, analyzed and published it?_ --> You make it available for others!

In [56]:
import pandas as pd
import numpy as np

In [70]:
animals = pd.Series(['dog', 'cat', 'horse', 'mouse', 'otter', 'fox', 'cobra', None]) # Panda series: 1d array
print(animals)

0      dog
1      cat
2    horse
3    mouse
4    otter
5      fox
6    cobra
7      NaN
dtype: str

In [86]:
sports = pd.Series({'Football':'America', 'Sjoelen':'Nederland', 'Fierljeppen':'Fries'})
print(sports)
print("\n",sports.iloc[[0,2]]) #get America and Fries

Football         America
Sjoelen        Nederland
Fierljeppen        Fries
dtype: str

 Football       America
Fierljeppen      Fries
dtype: str

In [81]:
sports.iloc[[0,2]]

Football       America
Fierljeppen      Fries
dtype: str

In [123]:
## Dataframes
purchase_1 = pd.Series({"Name":"Kees", "Item":"Dog Food", "Cost":22.50})
purchase_2 = pd.Series({"Name":"Kevin", "Item":"Kitty Litter", "Cost":2.50})
purchase_3 = pd.Series({"Name":"Merel", "Item":"Aston Martin", "Cost":97000.00})
purchase_4 = pd.Series({"Name":"Karel", "Item":"Bird Seed", "Cost":5.00})

df = pd.DataFrame(data = [purchase_1, purchase_2, purchase_3, purchase_4],
                  index = ['Series1', 'Series2', 'Series3', 'Series4'])

print(df)

          Name          Item     Cost
Series1   Kees      Dog Food     22.5
Series2  Kevin  Kitty Litter      2.5
Series3  Merel  Aston Martin  97000.0
Series4  Karel     Bird Seed      5.0

In [104]:
df.iloc[1:4, [1,2]]  # Slicing and indexing with iloc

                 Item     Cost
Series2  Kitty Litter      2.5
Series3  Aston Martin  97000.0
Series4     Bird Seed      5.0

In [107]:
df.describe() # obtains a quick statistical summary over all, or a specified column. Here there's only one.

               Cost
count      4.000000
mean   24257.500000
std    48495.000816
min        2.500000
25%        4.375000
50%       13.750000
75%    24266.875000
max    97000.000000

In [108]:
## Removing values
df.drop(['Series2'])

          Name          Item     Cost
Series1   Kees      Dog Food     22.5
Series3  Merel  Aston Martin  97000.0
Series4  Karel     Bird Seed      5.0

In [110]:
## However, this is not 'in place'. To make this change permanent, overwrite the dataframe:
df = df.drop('Series2') # OR df.drop('series2', inplace=True)

KeyError: "['Series2'] not found in axis"

In [111]:
df.drop('Cost', axis=1, inplace=True)

In [113]:
df.head() # prints the first 5 rows of the dataframe, just like the Linux command

          Name          Item
Series1   Kees      Dog Food
Series3  Merel  Aston Martin
Series4  Karel     Bird Seed

In [119]:
df.rename(columns={'Name':'Moniker'}, inplace=True) # Renames a column header to the second dictionary value
df

        Moniker          Item
Series1    Kees      Dog Food
Series3   Merel  Aston Martin
Series4   Karel     Bird Seed

In [124]:
## Reload the dataframe in its entirity before executing this cell.
df['Cost'] > 5

Series1     True
Series2    False
Series3     True
Series4    False
Name: Cost, dtype: bool

In [129]:
df[(df['Cost'] > 2) & (df['Cost'] < 70)] # Multiple conditions are separated by round brackets

          Name          Item  Cost
Series1   Kees      Dog Food  22.5
Series2  Kevin  Kitty Litter   2.5
Series4  Karel     Bird Seed   5.0