## Exercise pandas

The TB_burden_age_sex_2019-04-23.csv for 2017 from the site https://www.who.int/tb/country/data/download/en/ can be found on the data folder. In this exercise you will open the file with `pd.read_csv()` method and do the following cleaning

- drop the collumns iso2, iso3, iso_numeric. 
- rename the collumn age_group to age

After that you answer the questions 0 to 4.

In [1]:
import pandas as pd

In [56]:
df = pd.read_csv('data/TB_burden_age_sex_2019-04-23.csv')
df.head()

,country,iso2,iso3,iso_numeric,year,measure,unit,age_group,sex,best,lo,hi
0,Afghanistan,AF,AFG,4,2017,inc,num,0-14,a,7500,4300.0,11000.0
1,Afghanistan,AF,AFG,4,2017,inc,num,0-14,f,3600,1400.0,5800.0
2,Afghanistan,AF,AFG,4,2017,inc,num,0-14,m,4000,1500.0,6400.0
3,Afghanistan,AF,AFG,4,2017,inc,num,0-4,f,1800,0.0,4400.0
4,Afghanistan,AF,AFG,4,2017,inc,num,0-4,m,2200,0.0,5400.0

In [57]:
## Begin by dropping the required columns, first checking our work by not overwriting, then adding inplace=True
df.drop(['iso2', 'iso3', 'iso_numeric'], axis=1, inplace=True)

In [58]:
## Now rename the age_group column to 'age'
df.rename(columns={"age_group":"age"}, inplace=True)

In [59]:
df.head()

       country  year measure unit   age sex  best      lo       hi
0  Afghanistan  2017     inc  num  0-14   a  7500  4300.0  11000.0
1  Afghanistan  2017     inc  num  0-14   f  3600  1400.0   5800.0
2  Afghanistan  2017     inc  num  0-14   m  4000  1500.0   6400.0
3  Afghanistan  2017     inc  num   0-4   f  1800     0.0   4400.0
4  Afghanistan  2017     inc  num   0-4   m  2200     0.0   5400.0

### Question 0 (Example)

What is the first country in your dataframe df? This function should return a Series

In [60]:
def answer_zero(df):

    return df.iloc[0]

answer_zero(df)

country    Afghanistan
year              2017
measure            inc
unit               num
age               0-14
sex                  a
best              7500
lo              4300.0
hi             11000.0
Name: 0, dtype: object

### Question 1

Which country has the highest estimate of TB?

This function should return a the string India.

In [67]:
def answer_one(df):
    highest_TB_country = df.loc[df['hi'].idxmax()].country
    #df.sort_values('best', ascending=False, inplace=False)

    return highest_TB_country

print(f'Country with highest estimate of TB: {answer_one(df)}')

Country with highest estimate of TB: India

### Question 2

Which country has the smallest difference between high and low estimates?

In [76]:
def answer_two(df):
    diff_high_low = df['hi'] - df['lo'] #panda series of the differences
    smallest_diff_country = df.loc[diff_high_low.idxmin()].country
    
    return smallest_diff_country #write your code here, should return American Samoa

answer_two(df)

'American Samoa'

### Question 3

How many countries have 65plus records?

In [98]:
def answer_three(df):
    countries_with_65plus = df.loc[df['age']=='65plus'].country
    unique_countries = countries_with_65plus.unique()
    return unique_countries.size

answer_three(df)

119

### Question 4

Select the females and exclude the 'age = all' records. What are the top 5 countries that have the two most highest 'best estimates'?

In [123]:
#write your code here, should return this
"""
India          1084000
Indonesia       393000
China           296000
Pakistan        252000
Philippines     173000
"""

df_subset = df.loc[(df['sex']=='f') & (df['age'] != 'all')] # select the females and exclude the age=all records
df_f_bycountry = df_subset.groupby('country')               # grouped by country
two_bests = df_f_bycountry['best'].nlargest(2)
countries_twobest_summed = two_bests.groupby('country').sum()

highest_countries = countries_twobest_summed.nlargest(5)

print(highest_countries)

country
India          1084000
Indonesia       393000
China           296000
Pakistan        252000
Philippines     173000
Name: best, dtype: int64